services:
    perform_dashboard.listener.menu:
        class: Perform\BaseBundle\EventListener\SimpleMenuListener
        arguments:
            - 'dashboard'
            - null
            - 'perform_dashboard_dashboard_index'
            - 'dashboard'
        tags:
            - { name: kernel.event_listener, event: perform_base.menu.build, method: onMenuBuild }
